minor refactors.

diff --git a/devOps/Dockerfile.msb b/devOps/Dockerfile.msb
--- a/devOps/Dockerfile.msb
+++ b/devOps/Dockerfile.msb
@@ -42,16 +42,18 @@ ENV PYTHONUNBUFFERED=1 \
     PIP_PYPI_URL=https://pypi.org/simple \
     LD_LIBRARY_PATH=/usr/local/lib/python3.12/dist-packages/nvidia/cublas/lib:$LD_LIBRARY_PATH
 
-# Copy and install Python dependencies
+# Copy Python dependencies list
 COPY requirements.txt requirements.txt
+COPY saveModels.py saveModels.py
+# Create model directory
+RUN mkdir -p /app/jinv3/modelCache
 
-# Install dependencies and immediately clean up to reduce image size
+# Install dependencies and immediately clean up in one layer to reduce image size
 RUN apt-get update && apt-get install -y --no-install-recommends \
     python3.12 \
     python3-pip \
     libjpeg-dev \
     zlib1g-dev \
-    python3-dev \
     libomp-dev \
     libclblast-dev \
     libopenblas-dev \
@@ -63,12 +65,14 @@ RUN apt-get update && apt-get install -y --no-install-recommends \
     update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1 && \
     update-alternatives --config python3 && \
     pip3 install --debug --no-cache-dir --verbose --break-system-packages --index-url https://download.pytorch.org/whl/cu126 torch && \
-    pip3 install --debug --no-cache-dir --verbose --upgrade --break-system-packages --index-url \ 
-    https://pypi.org/simple -r requirements.txt && \
-    apt-get purge -y build-essential && \
-    apt-get autoremove -y && \
+    pip3 install --debug --no-cache-dir  --upgrade --break-system-packages --index-url https://pypi.org/simple -r requirements.txt && \
+    python3 saveModels.py && \
+    curl -o /app/Phi-3.5-mini-instruct-Q6_K.gguf -L \
+    "https://huggingface.co/bartowski/Phi-3.5-mini-instruct-GGUF/resolve/main/Phi-3.5-mini-instruct-Q6_K.gguf" || \
+    { echo "Failed to download LLM model" && exit 1; } && \
+    apt-get autoremove --purge  -y && \
     apt-get clean -y && \
-    rm -rf /root/.cache /tmp/* /var/tmp/* /var/lib/apt/lists/*
+    rm -rf /root/.cache/* /tmp/* /var/tmp/* /var/lib/apt/lists/*
 
 # Copy llama-cpp libraries compiled with cuda from build local path
 COPY --from=builder /usr/local/lib/python3.12/dist-packages/llama_cpp /usr/local/lib/python3.12/dist-packages/llama_cpp
@@ -76,15 +80,3 @@ COPY --from=builder  /usr/local/lib/python3.12/dist-packages/llama_cpp_python-0.
 COPY --from=builder /usr/local/lib/python3.12/dist-packages/lib /usr/local/lib/python3.12/dist-packages/lib
 COPY --from=builder /usr/local/lib/python3.12/dist-packages/include /usr/local/lib/python3.12/dist-packages/include
 
-# Create model directory and download model
-RUN mkdir -p /app/jinv3/modelCache
-
-# Copy script and download model inside a single RUN layer
-COPY saveModels.py saveModels.py
-RUN python3 saveModels.py && \
-    curl -o /app/Phi-3.5-mini-instruct-Q6_K.gguf -L \
-    "https://huggingface.co/bartowski/Phi-3.5-mini-instruct-GGUF/resolve/main/Phi-3.5-mini-instruct-Q6_K.gguf" || \
-    { echo "Failed to download LLM model" && exit 1; } && \
-    apt-get autoremove -y && \
-    apt-get clean -y && \
-    rm -rf /root/.cache/* /tmp/* /var/tmp/* /var/lib/apt/lists/*
