add required packages and seprate cuda supported torch install

diff --git a/Dockerfile.phi35Rag b/Dockerfile.phi35Rag
--- a/Dockerfile.phi35Rag
+++ b/Dockerfile.phi35Rag
@@ -16,14 +16,25 @@ COPY requirements.txt requirements.txt
 
 # Install dependencies and immediately clean up to reduce image size
 RUN apt-get update && apt-get install -y --no-install-recommends \
+    libomp-dev \
+    python3 \
+    python3-pip \
     build-essential \
-    python3 python3-pip \
-    libomp-dev libjpeg-dev zlib1g-dev python3-dev \
-    ninja-build libclblast-dev libopenblas-dev \
-    wget git curl && \
+    libjpeg-dev \
+    zlib1g-dev \
+    python3-dev \
+    ninja-build \
+    libclblast-dev \
+    libopenblas-dev \
+    libomp-dev \
+    libgomp1 \
+    wget \
+    git \
+    curl && \
     CMAKE_ARGS="-DGGML_NATIVE=OFF -DCMAKE_CXX_FLAGS='-march=native' -DCMAKE_C_FLAGS='-march=native' -DGGML_CPU_ARM_ARCH=native" pip install --debug --no-cache-dir --verbose --break-system-packages \
     --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cuda125 llama-cpp-python && \
     pip install --debug --no-cache-dir --verbose --upgrade --break-system-packages --index-url https://pypi.org/simple -r requirements.txt && \
+    pip install --debug --no-cache-dir --verbose --break-system-packages --extra-index-url https://download.pytorch.org/whl/cu126 torch && \
     apt-get purge -y build-essential && \
     apt-get autoremove -y && \
     apt-get clean -y && \
@@ -40,5 +51,8 @@ COPY saveModels.py saveModels.py
 RUN python3 saveModels.py && \
     curl -o /app/Phi-3.5-mini-instruct-Q6_K.gguf -L \
     "https://huggingface.co/bartowski/Phi-3.5-mini-instruct-GGUF/resolve/main/Phi-3.5-mini-instruct-Q6_K.gguf" || \
-    { echo "Failed to download LLM model" && exit 1; }
+    { echo "Failed to download LLM model" && exit 1; } && \
+    apt-get autoremove -y && \
+    apt-get clean -y && \
+    rm -rf /root/.cache/* /tmp/* /var/tmp/* /var/lib/apt/lists/*
 
